/* Generated By:JavaCC: Do not edit this line. AbjadParserTokenManager.java */
import java.util.*;

/** Token Manager. */
public class AbjadParserTokenManager implements AbjadParserConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1800000000L) != 0L)
            return 57;
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 33;
            return 57;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 32:
         jjmatchedKind = 1;
         return jjMoveStringLiteralDfa1_0(0xc0000000000L);
      case 34:
         return jjStopAtPos(0, 9);
      case 37:
         return jjStartNfaWithStates_0(0, 36, 57);
      case 44:
         return jjStopAtPos(0, 29);
      case 45:
         return jjMoveStringLiteralDfa1_0(0x20000000000L);
      case 58:
         return jjStopAtPos(0, 28);
      case 94:
         return jjStartNfaWithStates_0(0, 35, 57);
      default :
         return jjMoveNfa_0(6, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStopAtPos(1, 41);
         break;
      case 123:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000L);
      case 125:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStopAtPos(1, 43);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 32:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(2, 42);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x8000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec1 = {
   0x0L, 0x20L, 0x0L, 0x0L
};
static final long[] jjbitVec2 = {
   0x0L, 0x10L, 0x0L, 0x0L
};
static final long[] jjbitVec3 = {
   0x80000000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec4 = {
   0x400000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec5 = {
   0x200000000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec6 = {
   0x10000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec7 = {
   0x40000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec9 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0x0L, 0x0L
};
static final long[] jjbitVec10 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec11 = {
   0x1000000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec12 = {
   0x2000000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec13 = {
   0x0L, 0x8L, 0x0L, 0x0L
};
static final long[] jjbitVec14 = {
   0x0L, 0x4L, 0x0L, 0x0L
};
static final long[] jjbitVec15 = {
   0x100000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec16 = {
   0x0L, 0x200L, 0x0L, 0x0L
};
static final long[] jjbitVec17 = {
   0x0L, 0x100L, 0x0L, 0x0L
};
static final long[] jjbitVec18 = {
   0x20000000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec19 = {
   0x200000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec20 = {
   0x0L, 0x400L, 0x0L, 0x0L
};
static final long[] jjbitVec21 = {
   0x0L, 0x2L, 0x0L, 0x0L
};
static final long[] jjbitVec22 = {
   0x10000000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec23 = {
   0x0L, 0x40L, 0x0L, 0x0L
};
static final long[] jjbitVec24 = {
   0x20000000000L, 0x0L, 0x0L, 0x0L
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 185;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 6:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 6)
                        kind = 6;
                     jjCheckNAddStates(0, 2);
                  }
                  else if ((0x5000000000000000L & l) != 0L)
                  {
                     if (kind > 37)
                        kind = 37;
                  }
                  else if ((0x840000000000L & l) != 0L)
                  {
                     if (kind > 34)
                        kind = 34;
                  }
                  else if ((0x280000000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                  }
                  else if (curChar == 33)
                     jjAddStates(3, 4);
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 64;
                  else if (curChar == 37)
                     jjCheckNAdd(57);
                  else if (curChar == 61)
                  {
                     if (kind > 38)
                        kind = 38;
                  }
                  else if (curChar == 41)
                  {
                     if (kind > 8)
                        kind = 8;
                  }
                  else if (curChar == 40)
                  {
                     if (kind > 7)
                        kind = 7;
                  }
                  if (curChar == 60)
                     jjCheckNAddTwoStates(54, 184);
                  else if (curChar == 62)
                     jjCheckNAddTwoStates(54, 182);
                  else if (curChar == 47)
                     jjCheckNAdd(57);
                  else if (curChar == 42)
                     jjCheckNAdd(57);
                  else if (curChar == 45)
                     jjCheckNAdd(57);
                  else if (curChar == 43)
                     jjCheckNAdd(57);
                  else if (curChar == 61)
                     jjCheckNAdd(54);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjCheckNAddStates(0, 2);
                  break;
               case 1:
                  if (curChar != 46)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjCheckNAddTwoStates(2, 3);
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjCheckNAddTwoStates(2, 3);
                  break;
               case 4:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(5);
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjCheckNAdd(5);
                  break;
               case 7:
                  if (curChar == 41 && kind > 8)
                     kind = 8;
                  break;
               case 51:
                  if ((0x280000000000L & l) != 0L && kind > 33)
                     kind = 33;
                  break;
               case 52:
                  if ((0x840000000000L & l) != 0L && kind > 34)
                     kind = 34;
                  break;
               case 53:
                  if ((0x5000000000000000L & l) != 0L && kind > 37)
                     kind = 37;
                  break;
               case 54:
                  if (curChar == 61 && kind > 37)
                     kind = 37;
                  break;
               case 55:
                  if (curChar == 61)
                     jjCheckNAdd(54);
                  break;
               case 56:
               case 57:
                  if (curChar == 61 && kind > 38)
                     kind = 38;
                  break;
               case 58:
                  if (curChar == 43)
                     jjCheckNAdd(57);
                  break;
               case 59:
                  if (curChar == 45)
                     jjCheckNAdd(57);
                  break;
               case 60:
                  if (curChar == 42)
                     jjCheckNAdd(57);
                  break;
               case 61:
                  if (curChar == 47)
                     jjCheckNAdd(57);
                  break;
               case 62:
                  if (curChar == 37)
                     jjCheckNAdd(57);
                  break;
               case 64:
                  if (curChar == 38 && kind > 39)
                     kind = 39;
                  break;
               case 65:
                  if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 70:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjAddStates(5, 6);
                  break;
               case 72:
                  if (curChar == 33)
                     jjAddStates(3, 4);
                  break;
               case 73:
                  if (curChar == 33)
                     jjCheckNAddStates(7, 9);
                  break;
               case 74:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(7, 9);
                  break;
               case 75:
                  if ((0x2400L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 76:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 77:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 78:
                  if (curChar == 62 && kind > 37)
                     kind = 37;
                  break;
               case 107:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 181:
                  if (curChar == 62)
                     jjCheckNAddTwoStates(54, 182);
                  break;
               case 182:
                  if (curChar == 62 && kind > 39)
                     kind = 39;
                  break;
               case 183:
                  if (curChar == 60)
                     jjCheckNAddTwoStates(54, 184);
                  break;
               case 184:
                  if (curChar == 60 && kind > 39)
                     kind = 39;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 6:
                  if ((0x2000000020000000L & l) != 0L)
                  {
                     if (kind > 8)
                        kind = 8;
                  }
                  else if ((0x800000008000000L & l) != 0L)
                  {
                     if (kind > 7)
                        kind = 7;
                  }
                  else if (curChar == 111)
                     jjAddStates(10, 11);
                  else if (curChar == 116)
                     jjAddStates(12, 13);
                  else if (curChar == 112)
                     jjAddStates(14, 15);
                  else if (curChar == 102)
                     jjAddStates(16, 19);
                  else if (curChar == 101)
                     jjAddStates(20, 21);
                  else if (curChar == 105)
                     jjAddStates(22, 23);
                  else if (curChar == 126)
                  {
                     if (kind > 39)
                        kind = 39;
                  }
                  else if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 66;
                  else if (curChar == 94)
                     jjstateSet[jjnewStateCnt++] = 57;
                  else if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 45;
                  else if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 42;
                  else if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 37;
                  else if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 31;
                  else if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 27;
                  else if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 20;
                  else if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 3:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(24, 25);
                  break;
               case 7:
                  if ((0x2000000020000000L & l) != 0L && kind > 8)
                     kind = 8;
                  break;
               case 13:
                  if (curChar == 101 && kind > 12)
                     kind = 12;
                  break;
               case 14:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 100 && kind > 14)
                     kind = 14;
                  break;
               case 19:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 25:
                  if (curChar == 114 && kind > 21)
                     kind = 21;
                  break;
               case 26:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if (curChar == 108 && kind > 23)
                     kind = 23;
                  break;
               case 30:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if (curChar == 110 && kind > 24)
                     kind = 24;
                  break;
               case 34:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 36:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if (curChar == 108 && kind > 25)
                     kind = 25;
                  break;
               case 40:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 41:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 42:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 43:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 44:
                  if (curChar == 114 && kind > 26)
                     kind = 26;
                  break;
               case 45:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 63:
                  if (curChar == 94)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 66:
                  if (curChar == 124 && kind > 39)
                     kind = 39;
                  break;
               case 67:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 68:
                  if (curChar == 126 && kind > 39)
                     kind = 39;
                  break;
               case 71:
                  if (curChar != 95)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 74:
                  jjAddStates(7, 9);
                  break;
               case 96:
                  if (curChar == 105)
                     jjAddStates(22, 23);
                  break;
               case 97:
                  if (curChar == 102 && kind > 10)
                     kind = 10;
                  break;
               case 98:
                  if (curChar == 116 && kind > 19)
                     kind = 19;
                  break;
               case 99:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 111:
                  if (curChar == 101)
                     jjAddStates(20, 21);
                  break;
               case 112:
                  if (curChar == 101 && kind > 11)
                     kind = 11;
                  break;
               case 113:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 114:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 115:
                  if (curChar == 115 && kind > 18)
                     kind = 18;
                  break;
               case 116:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if (curChar == 102)
                     jjAddStates(16, 19);
                  break;
               case 119:
                  if (curChar == 114 && kind > 13)
                     kind = 13;
                  break;
               case 120:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if (curChar == 101 && kind > 17)
                     kind = 17;
                  break;
               case 122:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 123:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 124:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 125:
                  if (curChar == 116 && kind > 20)
                     kind = 20;
                  break;
               case 126:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 110 && kind > 27)
                     kind = 27;
                  break;
               case 130:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if (curChar == 112)
                     jjAddStates(14, 15);
                  break;
               case 132:
                  if (curChar == 116 && kind > 15)
                     kind = 15;
                  break;
               case 133:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 135:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 136:
                  if (curChar == 114 && kind > 22)
                     kind = 22;
                  break;
               case 137:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 139:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 140:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 141:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 147:
                  if (curChar == 116)
                     jjAddStates(12, 13);
                  break;
               case 148:
                  if (curChar == 101 && kind > 16)
                     kind = 16;
                  break;
               case 149:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 150:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 151:
                  if (curChar == 111 && kind > 32)
                     kind = 32;
                  break;
               case 176:
                  if (curChar == 111)
                     jjAddStates(10, 11);
                  break;
               case 177:
                  if (curChar == 101 && kind > 30)
                     kind = 30;
                  break;
               case 178:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 179:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 178;
                  break;
               case 180:
                  if (curChar == 102 && kind > 31)
                     kind = 31;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 6:
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 11;
                  if (jjCanMove_4(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 23;
                  if (jjCanMove_7(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 49;
                  if (jjCanMove_8(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 40)
                        kind = 40;
                     jjCheckNAddStates(26, 28);
                  }
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(29, 34);
                  if (jjCanMove_16(hiByte, i1, i2, l1, l2))
                     jjAddStates(35, 36);
                  if (jjCanMove_17(hiByte, i1, i2, l1, l2))
                     jjAddStates(37, 38);
                  if (jjCanMove_18(hiByte, i1, i2, l1, l2))
                     jjAddStates(39, 41);
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjAddStates(42, 46);
                  break;
               case 8:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 12)
                     kind = 12;
                  break;
               case 9:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 10:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 22:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 17)
                     kind = 17;
                  break;
               case 23:
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (jjCanMove_4(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 47:
                  if (jjCanMove_5(hiByte, i1, i2, l1, l2) && kind > 27)
                     kind = 27;
                  break;
               case 48:
                  if (jjCanMove_6(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 49:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 50:
                  if (jjCanMove_7(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 69:
                  if (!jjCanMove_8(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddStates(26, 28);
                  break;
               case 74:
                  if (jjCanMove_9(hiByte, i1, i2, l1, l2))
                     jjAddStates(7, 9);
                  break;
               case 79:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(29, 34);
                  break;
               case 80:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 10)
                     kind = 10;
                  break;
               case 81:
                  if (jjCanMove_10(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 82:
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2) && kind > 13)
                     kind = 13;
                  break;
               case 83:
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 84:
                  if (jjCanMove_12(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 85:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 14)
                     kind = 14;
                  break;
               case 86:
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 87:
                  if (jjCanMove_13(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if (jjCanMove_6(hiByte, i1, i2, l1, l2) && kind > 15)
                     kind = 15;
                  break;
               case 89:
                  if (jjCanMove_7(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 90:
                  if (jjCanMove_12(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 91:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2) && kind > 24)
                     kind = 24;
                  break;
               case 92:
                  if (jjCanMove_5(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (jjCanMove_14(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 94:
                  if (jjCanMove_15(hiByte, i1, i2, l1, l2) && kind > 32)
                     kind = 32;
                  break;
               case 95:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 100:
                  if (jjCanMove_16(hiByte, i1, i2, l1, l2))
                     jjAddStates(35, 36);
                  break;
               case 101:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 11)
                     kind = 11;
                  break;
               case 102:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 104:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 18)
                     kind = 18;
                  break;
               case 105:
                  if (jjCanMove_10(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 108:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 110:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 142:
                  if (jjCanMove_17(hiByte, i1, i2, l1, l2))
                     jjAddStates(37, 38);
                  break;
               case 143:
                  if (jjCanMove_18(hiByte, i1, i2, l1, l2) && kind > 16)
                     kind = 16;
                  break;
               case 144:
                  if (jjCanMove_18(hiByte, i1, i2, l1, l2) && kind > 19)
                     kind = 19;
                  break;
               case 145:
                  if (jjCanMove_19(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if (jjCanMove_18(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 152:
                  if (jjCanMove_18(hiByte, i1, i2, l1, l2))
                     jjAddStates(39, 41);
                  break;
               case 153:
                  if (jjCanMove_19(hiByte, i1, i2, l1, l2) && kind > 20)
                     kind = 20;
                  break;
               case 154:
                  if (jjCanMove_13(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 155:
                  if (jjCanMove_19(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if (jjCanMove_13(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 157:
                  if (jjCanMove_20(hiByte, i1, i2, l1, l2) && kind > 21)
                     kind = 21;
                  break;
               case 158:
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 159:
                  if (jjCanMove_15(hiByte, i1, i2, l1, l2) && kind > 25)
                     kind = 25;
                  break;
               case 160:
                  if (jjCanMove_7(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 161:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjAddStates(42, 46);
                  break;
               case 162:
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2) && kind > 22)
                     kind = 22;
                  break;
               case 163:
                  if (jjCanMove_21(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if (jjCanMove_16(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 165:
                  if (jjCanMove_19(hiByte, i1, i2, l1, l2) && kind > 23)
                     kind = 23;
                  break;
               case 166:
                  if (jjCanMove_13(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 167:
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 168:
                  if (jjCanMove_22(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 169:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2) && kind > 26)
                     kind = 26;
                  break;
               case 170:
                  if (jjCanMove_16(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               case 171:
                  if (jjCanMove_18(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 172:
                  if (jjCanMove_7(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 173:
                  if (jjCanMove_23(hiByte, i1, i2, l1, l2) && kind > 30)
                     kind = 30;
                  break;
               case 174:
                  if (jjCanMove_11(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 173;
                  break;
               case 175:
                  if (jjCanMove_22(hiByte, i1, i2, l1, l2) && kind > 31)
                     kind = 31;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 185 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   0, 1, 3, 73, 78, 70, 71, 74, 75, 77, 179, 180, 150, 151, 135, 141, 
   120, 124, 128, 130, 114, 117, 97, 99, 4, 5, 69, 70, 71, 81, 84, 87, 
   90, 93, 95, 103, 110, 143, 146, 156, 158, 160, 164, 168, 172, 174, 175, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec0[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec1[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_2(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_3(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec3[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_4(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec4[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_5(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec5[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_6(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec6[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_7(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec7[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_8(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
            return true;
      case 7:
         return ((jjbitVec9[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_9(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec10[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_10(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec11[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_11(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec12[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_12(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec13[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_13(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec14[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_14(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec15[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_15(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec16[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_16(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec17[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_17(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec18[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_18(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec19[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_19(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec20[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_20(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec21[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_21(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec22[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_22(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec23[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_23(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 6:
         return ((jjbitVec24[i2] & l2) != 0L);
      default :
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, "\42", null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, "\72", "\54", null, null, null, null, null, "\136", "\45", null, null, null, 
null, "\55\76", "\40\173\40", "\40\175", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xfffffffffc1L, 
};
static final long[] jjtoSkip = {
   0x3eL, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[185];
static private final int[] jjstateSet = new int[370];
static protected char curChar;
/** Constructor. */
public AbjadParserTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public AbjadParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 185; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 13 && (0x2600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
